# This workflow validates, deploys, and runs the specified bundle in the development branch
name: "PROD PR"

# Ensure that only a single job or workflow using the same concurrency group
# runs at a time.
concurrency: 1

# Trigger this workflow whenever a pull request is opened against the repo's
# qa branch or an existing pull request's head branch is updated.
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install mlflow
        pip install hyperopt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --disable=all --disable=F0001 --enable=syntax-error